### ISSUE TITLE
Fix namespace issue ?

### ISSUE THREAD

**Issue by YakupIpek** [danesparza/domainname-parser#7]
I like the library and it seems it does the job pretty well, thanks for it. But one thing is quite annoying. I can not use DomainName class without specifying full namespace prefix as below. 
```
            DomainName.Library.DomainName domain;
            if (DomainName.Library.DomainName.TryParse("http://www.domain.com", out domain))
                return domain;
```

My suggestion is rename DomainName.Library as DomainParser and i also suggest rename DomainName as Domain.

Thanks

**Comment by CREFaulk** [comment]
Me too! jk
This was also the first thing I noticed about the library.

**Comment by danesparza** [comment]
Great suggestion!  I'll see if I can get to that soon.  

I also accept pull requests.  :smile:

**Comment by CREFaulk** [comment]
Perhaps PublicSuffix.Library as a namespace? It'd require nuget downloaders to update their code though.

**Comment by danesparza** [comment]
Thanks for the suggestions -- I have refactored the projects and updated the NuGet package.

**Comment by CREFaulk** [comment]
Thanks for this!
