### ISSUE TITLE
Domain parser couldn't parse properly

### ISSUE THREAD

**Issue by YakupIpek** [danesparza/domainname-parser#8]
Domain parser is parsing this url  ladymoriartyinparis.blogspot.com.tr as below
Domain = ladymoriartyinparis
TLD = blogspot.com.tr

Why it couldnt parse it correctly for this domain ?

**Comment by danesparza** [comment]
That appears to be the correct parsing, according to the [public suffix list](https://publicsuffix.org/).  Look at the section near the bottom, labeled:

```
// Google, Inc.
// Submitted by Eduardo Vela <evn@google.com>
```
