### ISSUE TITLE
Suggestion: Extend to auto-update the public suffix list

### ISSUE THREAD

**Issue by CREFaulk** [danesparza/domainname-parser#9]
Obviously this can be done in PowerShell and windows task scheduler but having an auto-download/clear cache would be a good method to include. It could be called from whatever service is validating email addresses however the devs want to write it.

**Comment by horch004** [comment]
Hi,
The auto-update / time to live / expiration has just been implemented.

**Comment by danesparza** [comment]
Completed in danesparza/domainname-parser#10
